name: Java Backend CI

on:
  push:
    paths:
      - 'src/**'
      - 'pom.xml'
    branches: [ "main" ]
  pull_request:
    paths:
      - 'src/**'
      - 'pom.xml'
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./  # root folder where pom.xml is

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      - name: Build project with Maven
        run: mvn clean install

      - name: Run unit tests
        run: mvn test
