name: React Frontend CI

on:
  push:
    paths:
      - 'frontend/**'
      - 'frontend/package.json'
      - 'frontend/package-lock.json'
    branches: [ "main" ]
  pull_request:
    paths:
      - 'frontend/**'
      - 'frontend/package.json'
      - 'frontend/package-lock.json'
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache node modules and npm cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node

      - name: Configure npm to use legacy-peer-deps
        run: npm config set legacy-peer-deps true

      - name: Install dependencies with npm ci
        run: npm ci

      - name: Run tests
        run: npm test -- --watchAll=false
