name: React Frontend CI

on:
  push:
    branches: [ "**" ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-ci.yml'
  pull_request:
    branches: [ "**" ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-ci.yml'
  workflow_dispatch:

jobs:
  build:
    name: Build React Frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - run: npm install --legacy-peer-deps
      - run: npm run build

  test:
    name: Test React Frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    needs: build
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - run: npm install --legacy-peer-deps
      - run: npm test -- --ci --coverage --watchAll=false

  docker-build-and-push:
    name: Docker Build and Push
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: fatb0y13/react-jwt-login-frontend:latest