name: React Frontend CI

on:
  push:
    paths:
      - 'frontend/**'
      - 'frontend/package.json'
      - 'frontend/package-lock.json'
    branches: [ "main" ]
  pull_request:
    paths:
      - 'frontend/**'
      - 'frontend/package.json'
      - 'frontend/package-lock.json'
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node

      - name: Install dependencies with legacy peer deps
        run: npm ci --legacy-peer-deps

      - name: Run tests
        run: npm test -- --watchAll=false
